### ISSUE TITLE
Nice Work!

### ISSUE THREAD

**Issue by Miquest** [jwoglom/controlX2#4]
Hello,
It's good to see you programming on an alternative app to control the T:Slim X2 pump!
I still have a few suggestions, but I don't know whether they have already been implemented. 
Have you implemented a security prompt before you can deliver a bolus? This can be very helpful, especially with WearOS! 
And will the final version be able to broadcast the app's data to xDrip Plus? I know the basic function has priority, I program a lot myself and I know how difficult it is to implement new features, or to start a new project!
Thank you for providing us with this app!

 Best regards,
T.E.

**Comment by jwoglom** [comment]
Hi, thanks for reaching out!

>Have you implemented a security prompt before you can deliver a bolus?

Not yet, but I have opened https://github.com/jwoglom/controlX2/issues/5 to track adding this on the phone. In my opinion at least, on a watch requiring a passcode/etc seems of lower priority since a Wear OS device auto-locks whenever you take it off your wrist than on a phone.


>And will the final version be able to broadcast the app's data to xDrip Plus? 

Another good idea and thing to track. I need to get a bit more of an understanding of how AndroidAPS and other applications broadcast data into xDrip before knowing how to implement this properly. added: https://github.com/users/jwoglom/projects/1/views/1?pane=issue&itemId=20818572
